server:
     contextPath: /api
debug: true
spring:
    application:
      name: kotlin-react-boot-mysql-docker
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://mysql-standalone1:3306/test?useSSL=false
        username: testuser
        password: testuser@123
        hikari:
            initialization-fail-timeout: 0
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8InnoDBDialect
        database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
        generate-ddl: true
        show-sql: true
        hibernate:
            ddl-auto: create
